# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actuator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("actuator.proto", :syntax => :proto3) do
    add_message "Void" do
    end
    add_message "Response" do
      optional :success, :bool, 1
    end
    add_message "State" do
      optional :value, :int32, 1
    end
  end
end

Void = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Void").msgclass
Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Response").msgclass
State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("State").msgclass
